COE_MissionHeader {
 World "{2F5B7F43B64F903B}worlds/COE/Chernarus/COE2_Chernarus.ent"
 m_sName "COE2 - Chernarus"
 m_sAuthor "Kex"
 m_sDescription "Co-operative infantry gameplay with dynamic objectives for Arma Reforger."
 m_sDetails "Co-operative infantry gameplay with dynamic objectives for Arma Reforger. Next generation of Combat Ops Enhanced with inspiration from mbrdmn's Dynamic Recon Ops from Arma 3."\
 ""
 m_sIcon "{DD41F01E3256551C}Missions/ChernarusMinus5.edds"
 m_sLoadingScreen "{DD41F01E3256551C}Missions/ChernarusMinus5.edds"
 m_sPreviewImage "{DD41F01E3256551C}Missions/ChernarusMinus5.edds"
 m_sGameMode "#AR-CombatScenario_Name"
 m_iPlayerCount 8
}